name: NetherEnough

author: Sfiguz7

description: A Slimefun addon to add more content for the Nether

main: me.sfiguz7.netherenough.NetherEnough

depend: [Slimefun]

version: ${project.version}

api-version: 1.14
